# Generated by Django 3.1.2 on 2020-10-25 01:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Receipt',
            fields=[
                ('control_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_delivered', models.DateField(default=datetime.date.today)),
                ('consignee_signature', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('LTR', 'Letter'), ('PAR', 'Parcel'), ('PCK', 'Package'), ('BOX', 'Box')], default='LTR', max_length=3)),
                ('package_weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.TextField(primary_key=True, serialize=False)),
                ('origin_area', models.CharField(default='uncategorized', max_length=8)),
                ('destination_area', models.CharField(default='uncategorized', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_type', models.TextField(primary_key=True, serialize=False)),
                ('delivery_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weight_Cost_Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_weight', models.FloatField()),
                ('base_cost', models.FloatField()),
                ('increment_weight', models.FloatField()),
                ('increment_cost', models.FloatField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='delivery_tracker.route')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='delivery_tracker.service')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Request',
            fields=[
                ('control_number', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='delivery_tracker.customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='delivery_tracker.package')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='delivery_tracker.route')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='delivery_tracker.service')),
                ('weight_cost_matrix', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='delivery_tracker.weight_cost_matrix')),
            ],
        ),
    ]
