# Generated by Django 3.1.2 on 2020-10-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight_Cost_Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_weight', models.FloatField()),
                ('base_cost', models.FloatField()),
                ('increment_weight', models.FloatField()),
                ('increment_cost', models.FloatField()),
            ],
        ),
    ]
