# Generated by Django 3.1.2 on 2020-10-21 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Package_type',
            new_name='package_type',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Package_weight',
            new_name='package_weight',
        ),
        migrations.AddField(
            model_name='package',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_tracker.customer'),
        ),
    ]
