# Generated by Django 3.1.2 on 2020-10-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_tracker', '0002_weight_cost_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_request',
            name='weight_cost_matrix',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='delivery_tracker.weight_cost_matrix'),
        ),
    ]
