# Generated by Django 3.1.2 on 2020-10-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_tracker', '0003_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
