# Generated by Django 3.1.2 on 2020-10-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_tracker', '0004_auto_20201023_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.TextField(primary_key=True, serialize=False)),
                ('origin_area', models.CharField(max_length=8)),
                ('destination_area', models.CharField(max_length=8)),
            ],
        ),
    ]
