# Generated by Django 3.1.2 on 2020-10-24 00:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_tracker', '0006_auto_20201023_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Receipt',
            fields=[
                ('control_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_delivered', models.DateField(default=datetime.date.today)),
                ('consignee_signature', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='customer',
        ),
        migrations.CreateModel(
            name='Delivery_Request',
            fields=[
                ('control_number', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='delivery_tracker.customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='delivery_tracker.package')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='delivery_tracker.route')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='delivery_tracker.service')),
            ],
        ),
    ]
