# Generated by Django 3.1.2 on 2020-10-24 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_tracker', '0009_auto_20201024_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_request',
            name='total_cost',
        ),
    ]
